package Corba;


/**
* Corba/JoueurActionPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Corba.idl
* lundi 20 juin 2016 19 h 59 CEST
*/

public abstract class JoueurActionPOA extends org.omg.PortableServer.Servant
 implements Corba.JoueurActionOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("creerJoueur", new java.lang.Integer (0));
    _methods.put ("connecterJoueur", new java.lang.Integer (1));
    _methods.put ("deconnecterJoueur", new java.lang.Integer (2));
    _methods.put ("getScore", new java.lang.Integer (3));
    _methods.put ("listerJoueurs", new java.lang.Integer (4));
    _methods.put ("getClassement", new java.lang.Integer (5));
    _methods.put ("creerPartie", new java.lang.Integer (6));
    _methods.put ("ajouterJoueurPartie", new java.lang.Integer (7));
    _methods.put ("disconnectToPartie", new java.lang.Integer (8));
    _methods.put ("listerParties", new java.lang.Integer (9));
    _methods.put ("nbJoueurComplet", new java.lang.Integer (10));
    _methods.put ("comencerJeu", new java.lang.Integer (11));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // Corba/JoueurAction/creerJoueur
       {
         String identifiant = in.read_string ();
         String motDePasse = in.read_string ();
         boolean $result = false;
         $result = this.creerJoueur (identifiant, motDePasse);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // Corba/JoueurAction/connecterJoueur
       {
         String identifiant = in.read_string ();
         String motDePasse = in.read_string ();
         boolean $result = false;
         $result = this.connecterJoueur (identifiant, motDePasse);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 2:  // Corba/JoueurAction/deconnecterJoueur
       {
         String identifiant = in.read_string ();
         boolean $result = false;
         $result = this.deconnecterJoueur (identifiant);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // Corba/JoueurAction/getScore
       {
         String identifiant = in.read_string ();
         int $result = (int)0;
         $result = this.getScore (identifiant);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 4:  // Corba/JoueurAction/listerJoueurs
       {
         String identifiant = in.read_string ();
         String $result = null;
         $result = this.listerJoueurs (identifiant);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 5:  // Corba/JoueurAction/getClassement
       {
         String identifiant = in.read_string ();
         String $result = null;
         $result = this.getClassement (identifiant);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 6:  // Corba/JoueurAction/creerPartie
       {
         String identifiant = in.read_string ();
         int nbJoueurs = in.read_long ();
         int $result = (int)0;
         $result = this.creerPartie (identifiant, nbJoueurs);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 7:  // Corba/JoueurAction/ajouterJoueurPartie
       {
         String identifiant = in.read_string ();
         int idPartie = in.read_long ();
         boolean $result = false;
         $result = this.ajouterJoueurPartie (identifiant, idPartie);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 8:  // Corba/JoueurAction/disconnectToPartie
       {
         String identifiant = in.read_string ();
         int idPartie = in.read_long ();
         boolean $result = false;
         $result = this.disconnectToPartie (identifiant, idPartie);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 9:  // Corba/JoueurAction/listerParties
       {
         String identifiant = in.read_string ();
         String $result = null;
         $result = this.listerParties (identifiant);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       case 10:  // Corba/JoueurAction/nbJoueurComplet
       {
         int idPartie = in.read_long ();
         boolean $result = false;
         $result = this.nbJoueurComplet (idPartie);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 11:  // Corba/JoueurAction/comencerJeu
       {
         int idPartie = in.read_long ();
         String $result = null;
         $result = this.comencerJeu (idPartie);
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:Corba/JoueurAction:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public JoueurAction _this() 
  {
    return JoueurActionHelper.narrow(
    super._this_object());
  }

  public JoueurAction _this(org.omg.CORBA.ORB orb) 
  {
    return JoueurActionHelper.narrow(
    super._this_object(orb));
  }


} // class JoueurActionPOA
