package Corba;


/**
* Corba/JoueurAction.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Corba.idl
* lundi 20 juin 2016 19 h 59 CEST
*/

public interface JoueurAction extends JoueurActionOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface JoueurAction
